---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.cookies.name"

ignore_missing:
  - decidim.participatory_processes.scopes.global
  - decidim.accessibility.skip_button
  - layouts.decidim.header.*
  - layouts.decidim.footer.*
